books = [
  {
    "author": "Chinua Achebe",
    "category": "Fiction",
    "imageLink": "images/things-fall-apart.jpg",
    "link": "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
    "pages": 209,
    "title": "Things Fall Apart",
    "price": 10.99,
  },
  {
    "author": "Hans Christian Andersen",
    "category": "Fiction",
    "imageLink": "images/fairy-tales.jpg",
    "link": "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
    "pages": 50,
    "title": "Fairy tales",
    "price": 10.99,
  },
  {
    "author": "Dante Alighieri",
    "category": "Dystopian",
    "imageLink": "images/the-divine-comedy.jpg",
    "link": "https://en.wikipedia.org/wiki/Divine_Comedy\n",
    "pages": 20,
    "title": "The Divine Comedy",
    "price": 8.99,
  },
  {
    "author": "Unknown",
    "category": "Dystopian",
    "imageLink": "images/the-epic-of-gilgamesh.jpg",
    "link": "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
    "pages": 30,
    "title": "The Epic Of Gilgamesh",
    "price": 7.99,
  },
  {
    "author": "Unknown",
    "category": "Classics",
    "imageLink": "images/the-book-of-job.jpg",
    "link": "https://en.wikipedia.org/wiki/Book_of_Job\n",
    "pages": 40,
    "title": "The Book Of Job",
    "price": 11.99,
  },
  {
    "author": "Unknown",
    "category": "Classics",
    "imageLink": "images/one-thousand-and-one-nights.jpg",
    "link": "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
    "pages": 288,
    "title": "One Thousand and One Nights",
    "price": 11.99,
  },
  {
    "author": "Unknown",
    "category": "Classics",
    "imageLink": "images/njals-saga.jpg",
    "link": "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n",
    "pages": 384,
    "title": "Nj\u00e1l's Saga",
    "price": 11.99,
  },
  {
    "author": "Jane Austen",
    "category": "Classics",
    "imageLink": "images/pride-and-prejudice.jpg",
    "link": "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
    "pages": 226,
    "title": "Pride and Prejudice",
    "price": 11.99,
  },
  {
    "author": "Honor\u00e9 de Balzac",
    "category": "Classics",
    "imageLink": "images/le-pere-goriot.jpg",
    "link": "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
    "pages": 443,
    "title": "Le P\u00e8re Goriot",
    "price": 11.99,
  },
  {
    "author": "Samuel Beckett",
    "category": "Classics",
    "imageLink": "images/molloy-malone-dies-the-unnamable.jpg",
    "link": "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
    "pages": 256,
    "title": "Molloy, Malone Dies, The Unnamable, the trilogy",
    "price": 11.99,
  },
  {
    "author": "Giovanni Boccaccio",
    "category": "Science Fiction",
    "imageLink": "images/the-decameron.jpg",
    "link": "https://en.wikipedia.org/wiki/The_Decameron\n",
    "pages": 1024,
    "title": "The Decameron",
    "price": 11.99,
  },
  {
    "author": "Jorge Luis Borges",
    "category": "Science Fiction",
    "imageLink": "images/ficciones.jpg",
    "link": "https://en.wikipedia.org/wiki/Ficciones\n",
    "pages": 224,
    "title": "Ficciones",
    "price": 11.99,
  },
  {
    "author": "Emily Bront\u00eb",
    "category": "Fiction",
    "imageLink": "images/wuthering-heights.jpg",
    "link": "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
    "pages": 342,
    "title": "Wuthering Heights",
    "price": 11.99,
  },
  {
    "author": "Albert Camus",
    "category": "Fiction",
    "imageLink": "images/l-etranger.jpg",
    "link": "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
    "pages": 185,
    "title": "The Stranger",
    "price": 11.99,
  },
  {
    "author": "Paul Celan",
    "category": "Fiction",
    "imageLink": "images/poems-paul-celan.jpg",
    "link": "\n",
    "pages": 320,
    "title": "Poems",
    "price": 11.99,
  },
  {
    "author": "Louis-Ferdinand C\u00e9line",
    "category": "Fiction",
    "imageLink": "images/voyage-au-bout-de-la-nuit.jpg",
    "link": "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night\n",
    "pages": 49,
    "title": "Journey to the End of the Night",
    "price": 11.99,
  },
  {
    "author": "Miguel de Cervantes",
    "category": "Fiction",
    "imageLink": "images/don-quijote-de-la-mancha.jpg",
    "link": "https://en.wikipedia.org/wiki/Don_Quixote\n",
    "pages": 1056,
    "title": "Don Quijote De La Mancha",
    "price": 11.99,
  },
  {
    "author": "Geoffrey Chaucer",
    "category": "Fiction",
    "imageLink": "images/the-canterbury-tales.jpg",
    "link": "https://en.wikipedia.org/wiki/The_Canterbury_Tales\n",
    "pages": 544,
    "title": "The Canterbury Tales",
    "price": 11.99,
  },
  {
    "author": "Anton Chekhov",
    "category": "Fiction",
    "imageLink": "images/stories-of-anton-chekhov.jpg",
    "link": "https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov\n",
    "pages": 194,
    "title": "Stories",
    "price": 11.99,
  },
  {
    "author": "Joseph Conrad",
    "category": "Fiction",
    "imageLink": "images/nostromo.jpg",
    "link": "https://en.wikipedia.org/wiki/Nostromo\n",
    "pages": 320,
    "title": "Nostromo",
    "price": 11.99,
  },
  {
    "author": "Charles Dickens",
    "category": "Fiction",
    "imageLink": "images/great-expectations.jpg",
    "link": "https://en.wikipedia.org/wiki/Great_Expectations\n",
    "pages": 194,
    "title": "Great Expectations",
    "price": 11.99,
  },
  {
    "author": "Denis Diderot",
    "category": "Fiction",
    "imageLink": "images/jacques-the-fatalist.jpg",
    "link": "https://en.wikipedia.org/wiki/Jacques_the_Fatalist\n",
    "pages": 596,
    "title": "Jacques the Fatalist",
    "price": 11.99,
  },
  {
    "author": "Alfred D\u00f6blin",
    "category": "Fiction",
    "imageLink": "images/berlin-alexanderplatz.jpg",
    "link": "https://en.wikipedia.org/wiki/Berlin_Alexanderplatz\n",
    "pages": 600,
    "title": "Berlin Alexanderplatz",
    "price": 11.99,
  },
  {
    "author": "Fyodor Dostoevsky",
    "category": "Fiction",
    "imageLink": "images/crime-and-punishment.jpg",
    "link": "https://en.wikipedia.org/wiki/Crime_and_Punishment\n",
    "pages": 46,
    "title": "Crime and Punishment",
    "price": 11.99,
  },
  {
    "author": "Fyodor Dostoevsky",
    "category": "Fiction",
    "imageLink": "images/the-idiot.jpg",
    "link": "https://en.wikipedia.org/wiki/The_Idiot\n",
    "pages": 656,
    "title": "The Idiot",
    "price": 11.99,
  },
  {
    "author": "Fyodor Dostoevsky",
    "category": "Fiction",
    "imageLink": "images/the-possessed.jpg",
    "link": "https://en.wikipedia.org/wiki/Demons_(Dostoyevsky_novel)\n",
    "pages": 768,
    "title": "The Possessed",
    "price": 11.99,
  },
  {
    "author": "Fyodor Dostoevsky",
    "category": "Fiction",
    "imageLink": "images/the-brothers-karamazov.jpg",
    "link": "https://en.wikipedia.org/wiki/The_Brothers_Karamazov\n",
    "pages": 824,
    "title": "The Brothers Karamazov",
    "price": 11.99,
  },
  {
    "author": "George Eliot",
    "category": "Fiction",
    "imageLink": "images/middlemarch.jpg",
    "link": "https://en.wikipedia.org/wiki/Middlemarch\n",
    "pages": 800,
    "title": "Middlemarch",
    "price": 11.99,
  },
  {
    "author": "Ralph Ellison",
    "category": "Fiction",
    "imageLink": "images/invisible-man.jpg",
    "link": "https://en.wikipedia.org/wiki/Invisible_Man\n",
    "pages": 39,
    "title": "Invisible Man",
    "price": 11.99,
  },
  {
    "author": "Euripides",
    "category": "Fiction",
    "imageLink": "images/medea.jpg",
    "link": "https://en.wikipedia.org/wiki/Medea_(play)\n",
    "pages": 104,
    "title": "Medea",
    "price": 11.99,
  },
  {
    "author": "William Faulkner",
    "category": "Fiction",
    "imageLink": "images/absalom-absalom.jpg",
    "link": "https://en.wikipedia.org/wiki/Absalom,_Absalom!\n",
    "pages": 313,
    "title": "Absalom, Absalom!",
    "price": 11.99,
  },
  {
    "author": "William Faulkner",
    "category": "Fiction",
    "imageLink": "images/the-sound-and-the-fury.jpg",
    "link": "https://en.wikipedia.org/wiki/The_Sound_and_the_Fury\n",
    "pages": 326,
    "title": "The Sound and the Fury",
    "price": 11.99,
  },
]
